class Label_Ref():
    """Target corpus
    """

    def __init__(self) -> None:
        self.label = {'飘':{'word': 0, 'initial': 'p', 'initial_class': 1, 'final': 'iao', 'tone':0},
                      '方':{'word': 1, 'initial': 'f', 'initial_class': 3, 'final': 'ang', 'tone':0},
                      '丢':{'word': 2, 'initial': 'd', 'initial_class': 4, 'final':  'iu', 'tone':0},
                      '他':{'word': 3, 'initial': 't', 'initial_class': 5, 'final':   'a', 'tone':0},
                      '天':{'word': 4, 'initial': 't', 'initial_class': 5, 'final': 'ian', 'tone':0},
                      '光':{'word': 5, 'initial': 'g', 'initial_class': 8, 'final':'uang', 'tone':0},
                      '均':{'word': 6, 'initial': 'j', 'initial_class':11, 'final':  'vn', 'tone':0},
                      '缺':{'word': 7, 'initial': 'q', 'initial_class':12, 'final':  've', 'tone':0},
                      '出':{'word': 8, 'initial':'ch', 'initial_class':15, 'final':   'u', 'tone':0},
                      '说':{'word': 9, 'initial':'sh', 'initial_class':16, 'final':  'uo', 'tone':0},
                      '扔':{'word':10, 'initial': 'r', 'initial_class':17, 'final': 'eng', 'tone':0},
                      '三':{'word':11, 'initial': 's', 'initial_class':20, 'final':  'an', 'tone':0},
                      '没':{'word':12, 'initial': 'm', 'initial_class': 2, 'final':  'ei', 'tone':1},
                      '明':{'word':13, 'initial': 'm', 'initial_class': 2, 'final': 'ing', 'tone':1},
                      '年':{'word':14, 'initial': 'n', 'initial_class': 6, 'final': 'ian', 'tone':1},
                      '结':{'word':15, 'initial': 'j', 'initial_class':11, 'final':  'ie', 'tone':1},
                      '穷':{'word':16, 'initial': 'q', 'initial_class':12, 'final':'iong', 'tone':1},
                      '床':{'word':17, 'initial':'ch', 'initial_class':15, 'final':'uang', 'tone':1},
                      '人':{'word':18, 'initial': 'r', 'initial_class':17, 'final':  'en', 'tone':1},
                      '昨':{'word':19, 'initial': 'z', 'initial_class':18, 'final':  'uo', 'tone':1},
                      '从':{'word':20, 'initial': 'c', 'initial_class':19, 'final': 'ong', 'tone':1},
                      '才':{'word':21, 'initial': 'c', 'initial_class':19, 'final':  'ai', 'tone':1},
                      '随':{'word':22, 'initial': 's', 'initial_class':20, 'final':  'ui', 'tone':1},
                      '而':{'word':23, 'initial':'er', 'initial_class':23, 'final':  'er', 'tone':1},
                      '把':{'word':24, 'initial': 'b', 'initial_class': 0, 'final':   'a', 'tone':2},
                      '品':{'word':25, 'initial': 'p', 'initial_class': 1, 'final':  'in', 'tone':2},
                      '你':{'word':26, 'initial': 'n', 'initial_class': 6, 'final':   'i', 'tone':2},
                      '旅':{'word':27, 'initial': 'l', 'initial_class': 7, 'final':   'v', 'tone':2},
                      '两':{'word':28, 'initial': 'l', 'initial_class': 7, 'final':'iang', 'tone':2},
                      '缓':{'word':29, 'initial': 'h', 'initial_class':10, 'final': 'uan', 'tone':2},
                      '选':{'word':30, 'initial': 'x', 'initial_class':13, 'final': 'van', 'tone':2},
                      '准':{'word':31, 'initial':'zh', 'initial_class':14, 'final':  'un', 'tone':2},
                      '早':{'word':32, 'initial': 'z', 'initial_class':18, 'final':  'ao', 'tone':2},
                      '有':{'word':33, 'initial': 'y', 'initial_class':21, 'final':  'ou', 'tone':2},
                      '我':{'word':34, 'initial': 'w', 'initial_class':22, 'final':   'o', 'tone':2},
                      '耳':{'word':35, 'initial':'er', 'initial_class':23, 'final':  'er', 'tone':2},
                      '不':{'word':36, 'initial': 'b', 'initial_class': 0, 'final':   'u', 'tone':3},
                      '费':{'word':37, 'initial': 'f', 'initial_class': 3, 'final':  'ei', 'tone':3},
                      '第':{'word':38, 'initial': 'd', 'initial_class': 4, 'final':   'i', 'tone':3},
                      '个':{'word':39, 'initial': 'g', 'initial_class': 8, 'final':   'e', 'tone':3},
                      '看':{'word':40, 'initial': 'k', 'initial_class': 9, 'final':  'an', 'tone':3},
                      '快':{'word':41, 'initial': 'k', 'initial_class': 9, 'final': 'uai', 'tone':3},
                      '话':{'word':42, 'initial': 'h', 'initial_class':10, 'final':  'ua', 'tone':3},
                      '下':{'word':43, 'initial': 'x', 'initial_class':13, 'final':  'ia', 'tone':3},
                      '这':{'word':44, 'initial':'zh', 'initial_class':14, 'final':   'e', 'tone':3},
                      '上':{'word':45, 'initial':'sh', 'initial_class':16, 'final': 'ang', 'tone':3},
                      '要':{'word':46, 'initial': 'y', 'initial_class':21, 'final':  'ao', 'tone':3},
                      '问':{'word':47, 'initial': 'w', 'initial_class':22, 'final':  'en', 'tone':3}}